src/frontend/JasmineGraphFrontEnd.cpp, src/frontend/JasmineGraphFrontEndProtocol.cpp, src/partitioner/local/RDFPartitioner.cpp, src/partitioner/local/RDFPartitioner.h
Partially implemented RDFPartitioner & adrdf function
=> Branch shalika

.gitignore, CMakeLists.txt, README.md, main.cpp, run.sh, src/backend/JasmineGraphBackend.cpp, src/frontend/JasmineGraphFrontEnd.cpp, src/frontend/JasmineGraphFrontEnd.h, src/metadb/SQLiteDBInterface.cpp, src/server/JasmineGraphInstance.cpp, src/server/JasmineGraphServer.cpp, src/util/Utils.cpp, src/util/logger/Logger.cpp, src/util/logger/Logger.h
Note : Before building the project install spdlog by running the following command : 
**`apt-get install libspdlog-dev`**
=> Logging features with SpdLog

CMakeLists.txt, build.sh
Contains some of the changes in [this PR](https://github.com/miyurud/jasminegraph/pull/56).
- xerces-c
- flatbuffers
- jsoncpp
- metis
- spdlog
include methods has not changed.
=> Changed the cmake build process 

docker/Dockerfile
Metis bin path was updated incorrectly in the previous docker file and this commit includes the correct docker file
=> Issue fixing in metis bin file path for docker profile

src/frontend/JasmineGraphFrontEnd.cpp, src/server/JasmineGraphServer.cpp, src/server/JasmineGraphServer.h
In docker mode there was an issue when the partitions are assigned to workers it doesn't assigned properly. This code change will address that issue.
=> Code changes for proper assignment of partitions to worker

src/frontend/JasmineGraphFrontEnd.cpp
This change will log the already calculated triangle count algorithm execution time to the log file
=> Code changes to log the triangle count algorithm execution time

src/server/JasmineGraphServer.cpp
This code change introduces the volume mapping for worker aggregate directory in docker mode
=> Code fix to add worker aggregate directory volume mapping

src/frontend/JasmineGraphFrontEnd.cpp, src/frontend/JasmineGraphFrontEnd.h
Check graph operational status before training
=> Check graph operational status before training

GraphSAGE/graphsage/predict.py, src_python/fl_client.py, src_python/fl_client_shed.py, src_python/fl_server.py, src_python/fl_server_shed.py, src_python/mem.py, src_python/merge.py, src_python/models/supervised.py, src_python/models/unsupervised.py
This pull request contains python scripts related to the federated graph learning task
=> add ML python scripts

src/centralstore/incremental/NodeBlock.cpp, src/centralstore/incremental/NodeBlock.h, src/centralstore/incremental/NodeManager.cpp, src/centralstore/incremental/NodeManager.h, src/centralstore/incremental/PropertyLink.cpp, src/centralstore/incremental/PropertyLink.h, src/centralstore/incremental/RelationBlock.cpp, src/centralstore/incremental/RelationBlock.h, src/centralstore/incremental/Utils.cpp, src/util/logger/Logger.cpp, src/util/logger/Logger.h
In this PR:
- add incremental store implementation (Nodes, Index, Relations and Property DBs)
- Includes the improvements suggested in https://github.com/miyurud/jasminegraph/pull/104
=> incremental store implementation

README.md
Update Readme with information on running JasmineGraph using docker
=> Update Readme with information on running JasmineGraph using docker

conf/jasminegraph-server.properties, src/server/JasmineGraphServer.cpp, src/server/JasmineGraphServer.h
Add participant details to the aggregator.
=> Add participant details to the aggregator

src/server/JasmineGraphInstanceService.cpp, src/util/Utils.cpp, src/util/Utils.h
Fix build issues for https://github.com/miyurud/jasminegraph/pull/138
=> Fix build issues for PR #138

src/server/JasmineGraphServer.cpp, src/server/JasmineGraphServer.h
=> Out degree distribution fixes

src/server/JasmineGraphServer.cpp
This PR fixes an error message thrown during the startup of JasmineGraph.
=> Fix startup sql error

CMakeLists.txt, Dockerfile, src/server/JasmineGraphInstanceService.cpp, src/server/JasmineGraphServer.cpp
Updates for new base image with Python3.8 and stellargraph.
Wait for train initiate Python commands to complete.
=> Updates with stellargraph and wait for train initiate commands to complete.

.github/workflows/code-lint.yml, src/performance/metrics/StatisticCollector.cpp, src/server/JasmineGraphInstance.cpp, src/util/Utils.cpp
Fix high CPU usage
Set socket timeout options to avoid waiting for too long when creating a connection
=> Fix high CPU usage and set socket timeout

src/frontend/JasmineGraphFrontEnd.cpp, src/server/JasmineGraphInstanceProtocol.cpp, src/server/JasmineGraphServer.h
Fix build failure which resulted due to merging PR https://github.com/miyurud/jasminegraph/pull/168
=> Fix build failure

Dockerfile, run-docker.sh
Updated instructions in the jasminegraph documentation. https://docs.google.com/document/d/1j0UdxZVwPv4f13V9muCnWQN_m1zYO_3QNIfZ6Bt8Mk0
=> Changes For Enable Remote  Debugging

src/nativestore/NodeBlock.cpp, src/nativestore/NodeBlock.h, src/nativestore/NodeManager.cpp, src/nativestore/NodeManager.h, src/nativestore/RelationBlock.cpp
- Refactored error throws to error logs
- Refactored variable and method names
- Add function to write node indexes on node index db
- Add functions which are required for streaming algorithms
=> Add required methods in native store classes

src/backend/JasmineGraphBackend.cpp, src/backend/JasmineGraphBackend.h, src/frontend/JasmineGraphFrontEnd.cpp, src/frontend/JasmineGraphFrontEnd.h, src/frontend/core/executor/impl/TriangleCountExecutor.cpp, src/frontend/core/executor/impl/TriangleCountExecutor.h, src/frontend/core/factory/ExecutorFactory.cpp, src/frontend/core/factory/ExecutorFactory.h, src/frontend/core/scheduler/JobScheduler.cpp, src/frontend/core/scheduler/JobScheduler.h, src/metadb/SQLiteDBInterface.cpp, src/ml/trainer/JasmineGraphTrainingSchedular.cpp, src/partitioner/local/MetisPartitioner.cpp, src/partitioner/local/MetisPartitioner.h, src/partitioner/local/RDFPartitioner.cpp, src/partitioner/local/RDFPartitioner.h, src/performance/metrics/PerformanceUtil.cpp, src/performance/metrics/PerformanceUtil.h, src/query/algorithms/linkprediction/JasminGraphLinkPredictor.cpp, src/server/JasmineGraphInstance.h, src/server/JasmineGraphServer.cpp, src/server/JasmineGraphServer.h, src/util/Utils.cpp, src/util/Utils.h, src/util/scheduler/SchedulerService.h
Consider only after merging #224
=> Correct the usage of pointers of database objects

src/query/algorithms/triangles/Triangles.cpp, src/query/algorithms/triangles/Triangles.h, src/server/JasmineGraphInstanceService.cpp
Speedup `trian` operation by removing redundancies and optimizing.
=> Optimize TRIAN

conf/jasminegraph-server.properties, src/frontend/core/executor/impl/StreamingTriangleCountExecutor.cpp, src/localstore/incremental/JasmineGraphIncrementalLocalStore.cpp, src/nativestore/NodeManager.cpp, src/nativestore/NodeManager.h, src/query/algorithms/triangles/StreamingTriangles.cpp, src/query/algorithms/triangles/StreamingTriangles.h, src/server/JasmineGraphInstanceService.cpp, src/util/kafka/StreamHandler.cpp
- Extend streaming triangle to multiple partitions.
- Enhanced algorithm accuracy
- Fixed bugs
=> Extend streaming triangle to multiple partitions

conf/prometheus.yaml, docker-compose.yml, start-docker.sh, stop-docker.sh, test-docker.sh
This PR adds docker compose capabilities to JasmineGraph.
=> Add docker compose scripts

conf/jasminegraph-server.properties, stop-docker.sh
This resolves the issue of pushing metrics to Prometheus push gateway
=> Fix network issue

performance_tools/grafana_dashboard.json
Create a template file to import grafana dashboard to visualize jasminegraph performance
=> Create template for grafana performance dashboard

performance_tools/grafana_dashboard.json
Add multiple panels/charts to visualize metrics.
=> Jasminegraph_Dashboard: Grafana

src/server/JasmineGraphInstanceProtocol.cpp, src/server/JasmineGraphInstanceProtocol.h, src/server/JasmineGraphInstanceService.cpp, src/util/Utils.cpp
There was an issue with master worker communication, it is terminating before a file chunk is persisted. It is fixed.
=> Fix master-worker communication termination

docker-compose.yml, start-docker-with-loki.sh, start-docker.sh
Modification to shell scripts and docker-compose files
=> Grafana loki refactor

conf/jasminegraph-server.properties, config.alloy, docker-compose.yml, loki-config.yaml, src/frontend/core/executor/impl/PageRankExecutor.cpp, src/query/algorithms/linkprediction/JasminGraphLinkPredictor.cpp, src/query/algorithms/linkprediction/JasminGraphLinkPredictor.h, src/server/JasmineGraphServer.cpp, src/server/JasmineGraphServer.h, src/util/Conts.h, start-docker.sh, tests/unit/util/Utils_test.cpp
Resolves merge conflicts between Kafka streaming implementation and master branch's new monitoring stack (Alloy, Loki, Grafana).
- Resolved conflicts in [docker-compose.yml](vscode-file://vscode-app/snap/code/201/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) between existing Kafka services and newly added monitoring stack (Alloy, Loki, Grafana)
- Reassigned container IP addresses to prevent conflicts:
JasmineGraph: 172.28.5.5 → 172.28.5.7
Kafka: 172.28.5.4 → 172.28.5.8
- Updated all related configuration files to maintain consistency
=> Resolve merge conflicts with master branch for Kafka streaming integration

tests/integration/test.py
Did some modifications in the integration test to find out whether there are isuues
=> Minor change

Dockerfile
This will bump the JasmineGraph to a new prerequisites image.
=> Version Bump
